[package]
name = "impulsefy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
librespot-core = { version = "0.8", default-features = false, features = ["rustls-tls-webpki-roots"] }
librespot-playback = { version = "0.8", default-features = false, features = ["rustls-tls-webpki-roots"] }
librespot-connect = { version = "0.8", default-features = false }
librespot-metadata = { version = "0.8", default-features = false }
librespot-protocol = { version = "0.8", default-features = false }
jni = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "macros"] }

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = true
