[package]
name = "impulsefy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
librespot-core = { version = "0.8", default-features = false, features = ["rustls-tls-webpki-roots"] }
librespot-playback = { version = "0.8", default-features = false, features = ["rustls-tls-webpki-roots"] }
librespot-connect = { version = "0.8", default-features = false }
librespot-discovery = { version = "0.8", default-features = false, features = ["with-libmdns"] }
librespot-metadata = { version = "0.8", default-features = false }
librespot-protocol = { version = "0.8", default-features = false }
protobuf = "3"
protobuf-json-mapping = "3"
http = "1"
url = "2"
jni = "0.21"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "macros"] }

[build-dependencies]
protobuf-codegen = "3"

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = true

[patch.crates-io]
librespot-core = { path = "vendor/librespot-core" }
